# nmake makefile
# 
# Tools used:
#  Compile::Resource Compiler
#  Compile::GNU C
#  Make: nmake
all : nbbase.exe

nbbase.exe : nbbase.obj nbbase.res nbbase.def
	gcc -Zomf nbbase.obj nbbase.res nbbase.def -o nbbase.exe
	wrc nbbase.res

nbbase.obj : nbbase.c nbbase.h
	gcc -Wall -Zomf -c -O2 nbbase.c -o nbbase.obj

nbbase.res : nbbase.rc
	wrc -r nbbase.rc

clean :
	rm -rf *exe *res *obj *dll
